name: CI/CD - Teste e Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job de Testes
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Rodar os testes
        run: echo "Testes não configurados" # Nenhum teste real, apenas uma simulação

  # Job de Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success() # Só faz o deploy se os testes passarem
    
    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar dependências
        run: npm install

      - name: Fazer o build do site
        run: echo "Build do site (não implementado para este exemplo)"

      - name: Deploy para o Vercel
        run: |
          # Aqui você pode adicionar o comando para fazer o deploy
          # Exemplo: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
          echo "Deploy para Vercel (simulação)"
