name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: |
          npm install # Este comando vai instalar todas as dependências, incluindo o stylelint
      
      - name: Install tidy-html5
        run: sudo apt-get install tidy

      - name: Lint HTML
        run: tidy -errors index.html
      
      - name: Lint CSS
        run: npx stylelint "**/*.css" # Usando npx para garantir que o stylelint será executado corretamente
      
      - name: Lint JavaScript
        run: npx eslint "**/*.js" # Usando npx para garantir que o eslint será executado corretamente
