name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Dependencies
        run: |
          npm install -g eslint stylelint tidy-html5
          npm install stylelint-config-standard --save-dev
      
      - name: Install tidy-html5
        run: sudo apt-get install tidy

      - name: Lint HTML
        run: tidy -errors index.html
      
      - name: Lint CSS
        run: stylelint "**/*.css"
      
      - name: Lint JavaScript
        run: eslint "**/*.js"
